"""Thin wrapper around py-clob-client.

Read-only (Level 0, unauthenticated) access is all that's needed for paper
trading and market discovery -- Polymarket's CLOB allows unauthenticated
reads of order books, prices, and markets. Authenticated access (placing
real orders) is intentionally not wired up yet; see README for the deferred
live-trading phase.

py-clob-client's HTTP layer sets NO timeout on its requests (confirmed by
inspecting its source -- no "timeout" anywhere in http_helpers/). That means
a slow/degraded Polymarket endpoint can hang a call indefinitely, which
defeats core/scheduler.py's retry-on-failure design entirely: a hang never
raises an exception to be caught, it just stalls the process forever. Since
we can't pass a timeout into the library's calls directly, we set a
process-wide socket default here -- any socket opened anywhere in this
process (including inside py-clob-client) that doesn't specify its own
timeout falls back to this one.
"""
from __future__ import annotations

import os
import socket
from functools import lru_cache
from pathlib import Path

from dotenv import load_dotenv
from py_clob_client_v2.client import ClobClient
from py_clob_client_v2.clob_types import ApiCreds, BookParams

CLOB_HOST = "https://clob.polymarket.com"
POLYGON_CHAIN_ID = 137
DEFAULT_SOCKET_TIMEOUT_SECONDS = 15

socket.setdefaulttimeout(DEFAULT_SOCKET_TIMEOUT_SECONDS)

# Load .env once at import time (no-op if already set in environment)
load_dotenv(Path(__file__).resolve().parent.parent / ".env")


@lru_cache(maxsize=1)
def get_client() -> ClobClient:
    """Returns a shared read-only ClobClient instance (no auth, Level 0)."""
    return ClobClient(CLOB_HOST)


@lru_cache(maxsize=1)
def get_authenticated_client() -> ClobClient:
    """Returns a Level 2 authenticated ClobClient for order placement.

    Reads credentials from environment variables (loaded from .env above):
      POLY_PRIVATE_KEY      — MetaMask wallet private key (hex, with or without 0x)
      POLY_API_KEY          — generated by scripts/setup_credentials.py
      POLY_API_SECRET       — same
      POLY_API_PASSPHRASE   — same

    Raises KeyError with a clear message if any credential is missing.
    """
    missing = [k for k in ("POLY_PRIVATE_KEY", "POLY_API_KEY", "POLY_API_SECRET", "POLY_API_PASSPHRASE") if not os.environ.get(k)]
    if missing:
        raise KeyError(
            f"Missing live-trading credentials in .env: {', '.join(missing)}\n"
            "Run scripts/setup_credentials.py to generate API keys, then fill in .env"
        )
    # V2 deposit wallet — the address shown as maker/signer in all CLOB V2 orders
    deposit_wallet = os.environ.get("POLY_DEPOSIT_WALLET", "0xa23d2F995FD9C03AAC2eBefa79795Df2365CA32D")
    return ClobClient(
        CLOB_HOST,
        chain_id=POLYGON_CHAIN_ID,
        key=os.environ["POLY_PRIVATE_KEY"],
        creds=ApiCreds(
            api_key=os.environ["POLY_API_KEY"],
            api_secret=os.environ["POLY_API_SECRET"],
            api_passphrase=os.environ["POLY_API_PASSPHRASE"],
        ),
        signature_type=3,   # POLY_1271 -- required for V2 deposit wallet
        funder=deposit_wallet,
    )


def get_order_book(token_id: str):
    return get_client().get_order_book(token_id)


def get_order_books(token_ids: list[str]):
    params = [BookParams(token_id=tid) for tid in token_ids]
    return get_client().get_order_books(params)


def get_midpoint(token_id: str) -> float:
    result = get_client().get_midpoint(token_id)
    return float(result["mid"]) if isinstance(result, dict) else float(result)


def get_price(token_id: str, side: str = "BUY") -> float:
    result = get_client().get_price(token_id, side=side)
    return float(result["price"]) if isinstance(result, dict) else float(result)
